[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "llm>=0.35",
    "llm-sdk",
    "pydantic>=2.13.5",
]
[tool.uv.workspace]
members = [
    "llm_sdk"
]

[tool.uv.sources]
llm-sdk = { workspace = true, editable = true }
torch = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
